exec-once = qs -c noctalia-shell
exec-once = systemctl start --user opentabletdriver
exec-once = systemctl start --user vicinae
exec-once = systemctl start --user hyprpolkitagent

exec = $XDG_CONFIG_HOME/hypr/hyprland/scripts/lid.sh
