exec-once = $HOME/.local/bin/exec-desktop-shell.sh
exec-once = systemctl start --user opentabletdriver
exec-once = systemctl start --user vicinae
exec-once = systemctl start --user hyprpolkitagent

exec = $XDG_CONFIG_HOME/hypr/hyprland/scripts/lid.sh
