$mainMod = SUPER
$terminal = ghostty +new-window
$fileManager = nautilus
# $launcher = qs -c noctalia-shell ipc call launcher toggle
$launcher = vicinae toggle
$lockScreem = qs -c noctalia-shell ipc call lockScreen lock
