# Hyprland configuration

source = ./hyprland/vars.conf
source = ./hyprland/monitors.conf
source = ./hyprland/autostart.conf
source = ./hyprland/lookandfeel.conf
source = ./hyprland/input.conf
source = ./hyprland/bindings.conf
source = ./hyprland/windowrules.conf
