"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = '$container$nix_shell$username$hostname$directory$git_branch$character'

[character]
error_symbol = "[~>](red)"
success_symbol = "[~>](green)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = " "

[username]
format = "[$user]($style)"
show_always = true

[hostname]
format = "[@](dimmed white)[$hostname]($style) "
ssh_only = false
style = "bold blue"

[container]
format = '[$symbol(\($name\))]($style) '
symbol = ""

[nix_shell]
format = '[$symbol(\($name\))]($style) '
symbol = ""

[fill]
symbol = " "
