import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
opacity = 0.9

[font]
normal = { family = "JetbrainsMono", style = "Semibold" }
bold = { family = "JetbrainsMono", style = "Bold" }
size = 12
