unbind C-b
set -g prefix C-\;

bind x kill-pane
bind e split-window -v
bind o split-window -h
bind n new-window -c "$PWD"

bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

set -s escape-time 0
set -g history-limit 50000
set -g default-terminal "tmux-256color"
set -g base-index 1
set -g pane-base-index 1
set -g mouse on
set -g default-command $SHELL
set -g allow-passthrough on
set -g extended-keys on
set -g extended-keys-format csi-u


# --- Style ---
set -g status-style 'bg=default,fg=colour7'
set -g status-justify left
set -g status-left ''
set -g status-left-length 0
set -g status-right '#[fg=colour8]#S  #[fg=colour8]%H:%M '
set -g status-right-length 30

set -g @tab_active_bg 'colour4'
set -g @tab_active_fg 'colour0'
set -g @tab_inactive_bg 'colour8'
set -g @tab_inactive_fg 'colour15'

set -g window-status-separator ' '
set -g window-status-style 'bg=default'
set -g window-status-current-style 'bg=default,bold'
set -g window-status-activity-style 'fg=colour11,bold'
set -g window-status-bell-style 'fg=colour9,bold'

set -g window-status-format "#[fg=#{@tab_inactive_bg},bg=default]#[fg=#{@tab_inactive_fg},bg=#{@tab_inactive_bg}] #I #W #F #[fg=#{@tab_inactive_bg},bg=default]"
set -g window-status-current-format "#[fg=#{@tab_active_bg},bg=default]#[fg=#{@tab_active_fg},bg=#{@tab_active_bg},bold] #I #W #F #[fg=#{@tab_active_bg},bg=default]"
