"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = '$username$directory$git_branch$nix_shell$container$python$character'
line_break = false

[character]
error_symbol = "[~>](red)"
success_symbol = "[~>](green)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = " "

[username]
format = "[$user]($style) "
show_always = true

[container]
symbol = "📦"

[nix_shell]
format = '[$symbol (\($name\))]($style) '
symbol = "❄️"

[fill]
symbol = " "

[python]
format = "[\\(venv\\)](blue) "
detect_extensions = []
detect_folders = []
